[general]
live_config_reload = true

[window]
opacity = 0.94
blur = false
decorations = "buttonless"
# startup_mode = "maximized"
position = { x = 15, y = 100 }
dimensions = { columns = 130, lines = 35 }
dynamic_title = true
option_as_alt = "both"

[window.padding]
x = 1
y = 4

[font]
size = 16
normal = { family = "Monaspace Neon NF" }

# [font.normal]
# family = "JetBrainsMono Nerd Font"

[cursor]
style = { shape = "Block", blinking = "Off" }

[colors.primary]
background = "#0a0a0a"
foreground = "#d6d6d6"

[colors.cursor]
text = "#111111"
cursor = "#f5c2e7"

[colors.selection]
text = "#f8f8f2"
background = "#242630"

[colors.normal]
black   = "#282828"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#d4be98"

[colors.bright]
black   = "#7c6f64"
red     = "#ff7b72"
green   = "#b0c76f"
yellow  = "#e0af68"
blue    = "#83c092"
magenta = "#e2a4c0"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[mouse]
hide_when_typing = true
