# bat
# Autogenerated from man page /Users/gourav/.nix-profile/share/man/man1/bat.1.gz
complete -c bat -l highlight-line -d 'highlights line 40'
complete -c bat -l line-range -d 'prints lines 30 to 40'

