# gh-alias-import
# Autogenerated from man page /Users/gourav/.nix-profile/share/man/man1/gh-alias-import.1.gz
complete -c gh-alias-import -l clobber -d 'Overwrite existing aliases of the same name EXIT CODES 0: Successful executio…'

