# gh-extension-create
# Autogenerated from man page /Users/gourav/.nix-profile/share/man/man1/gh-extension-create.1.gz
complete -c gh-extension-create -l precompiled -d 'Create a precompiled extension'

