# gh-issue
# Autogenerated from man page /Users/gourav/.nix-profile/share/man/man1/gh-issue.1.gz
complete -c gh-issue -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

