# gh-org-list
# Autogenerated from man page /Users/gourav/.nix-profile/share/man/man1/gh-org-list.1.gz
complete -c gh-org-list -s L -l limit -d 'Maximum number of organizations to list ALIASES gh org ls EXIT CODES 0: Succe…'

