# gh-repo-license-view
# Autogenerated from man page /Users/gourav/.nix-profile/share/man/man1/gh-repo-license-view.1.gz
complete -c gh-repo-license-view -s w -l web -d 'Open https://choosealicense'

