# zoxide
# Autogenerated from man page /Users/gourav/.nix-profile/share/man/man1/zoxide.1.gz
complete -c zoxide -s h -l help -d 'Print help information'
complete -c zoxide -s V -l version -d 'Print version information'

