theme = "cc_theme"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
soft-wrap.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["diagnostics"]
right = [
  "position",
  "total-line-numbers",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "│"

[keys.normal]
# File operations
"Cmd-s" = ":w"
"Cmd-o" = ":open ~/.config/helix/config.toml"

# Editing
"Y" = ":clipboard-yank"
"ret" = ["open_below", "normal_mode"]
"A-x" = "@x<A-d>"       # Delete line without yanking

# Other
"C-S-esc" = "extend_line"

[keys.insert]
"A-x" = "normal_mode"

[keys.insert.j]
k = "normal_mode"        # jk to exit insert mode

[keys.normal.g]
a = "code_action"

[keys.normal.z]
j = "scroll_up"
k = "scroll_down"

[keys.normal."+"]
m = ":run-shell-command make"
c = ":run-shell-command cargo build"
t = ":run-shell-command cargo test"
